# -*- coding: utf-8 -*-
"""matrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sTa7snCJvuEyjLlUclavTrl3m0Gsgvmu
"""

def inmatrix(m,n):
    print("enter integer in  matrix row wise  :- ")
    a=[]
    for i in range(m):
        b=[]
        for k in range(n):
            j=int(input())
            b.append(j)
        a.append(b)
    return a


def prmatrix(a):
    for i in range(len(a)):
        for j in range(len(a[0])):
            print(a[i][j],end=" ")
        print()

def multiplymatrix(a,b):
    mul=[]
    for i in range(len(a)):
        l=[]
        for j in range(len(b[0])):
            result=0
            for k in range(len(b)):
                result=result+a[i][k]*b[k][j]
            l.append(result)
            result=0
        mul.append(l)
    return mul

def addmatrix(a,b):
    mul = []
    result = 0
    for i in range(len(a)):
        l = []
        for j in range(len(a[0])):
            result =  a[i][j] + b[i][j]
            l.append(result)
            result = 0
        mul.append(l)
    return mul


def submatrix(a,b):
    mul = []
    result = 0
    for i in range(len(a)):
        l = []
        for j in range(len(a[0])):
            result =  a[i][j] - b[i][j]
            l.append(result)
            result = 0
        mul.append(l)
    return mul

def transpose(m,n):
    mul = []
    result = 0
    for i in range(n):
        l = []
        for j in range(m):
            result =  a[j][i]
            l.append(result)
            result = 0
        mul.append(l)
    return mul
     



print(" enter  first matrix :-\n ")
m=int(input("enter a number of row of first matrix \t"))
n=int(input("enter a number of column of first matrix\t"))
a=inmatrix(m,n)
print(" enter second matrix :-\n ")
p=int(input("enter number of row of second matrix\t"))
q=int(input("enter a number of column of second matrix\t"))
b=inmatrix(p,q)
print(" first matrix is = ")
prmatrix(a)
print("second matrix = ")
prmatrix(b)


print(" \n 1. for multiplication \n 2. for addition \n 3. for subtraction\n 4. for transpose \n  enter your choise ")
t=int(input())

if (t==1):
    if(n==p):
        c = multiplymatrix(a, b)
        print("multiplication of matrix is =\n")
        prmatrix(c)
    else:
        print("multiplication can not be done \n")
elif (t==2):
    if ((m==p) & (n==q)):
        print("addition of matrix is =\n")
        d = addmatrix(a, b)
        prmatrix(d)
    else:
        print("order of matrix is not same ")
elif(t==3):
    if ((m==p) & (n==q)):
        print(" subtraction  of matrix is =\n")
        d =submatrix(a,b)
        prmatrix(d)
elif(t==4):
    print("trancepose  of 1st  matrix is =\n")
    v=transpose(m,n)
    prmatrix(v)
    print("\ntrancepose  of 2nd  matrix is =\n")
    z=transpose(p,q)
    prmatrix(z)
else:
    print("invalid choise")

